// HKU Mathematics Major — Course Database
const COURSES = [
    // === Science Foundation (Required) ===
    { code: "SCNC1111", name: "Scientific Method and Reasoning", credits: 6, category: "science", prerequisites: [] },
    { code: "SCNC1112", name: "Fundamentals of Modern Science", credits: 6, category: "science", prerequisites: [] },

    // === Math Disciplinary Core (Required) ===
    { code: "MATH1013", name: "University Mathematics II", credits: 6, category: "math-core", prerequisites: [] },
    { code: "MATH2012", name: "Fundamental Concepts of Mathematics", credits: 6, category: "math-core", prerequisites: ["MATH1013"] },
    { code: "MATH2101", name: "Linear Algebra I", credits: 6, category: "math-core", prerequisites: ["MATH1013"] },
    { code: "MATH2102", name: "Linear Algebra II", credits: 6, category: "math-core", prerequisites: ["MATH2101"] },
    { code: "MATH2211", name: "Multivariable Calculus", credits: 6, category: "math-core", prerequisites: ["MATH1013"] },
    { code: "MATH2241", name: "Introduction to Mathematical Analysis", credits: 6, category: "math-core", prerequisites: ["MATH1013"] },

    // === Advanced Core (Required) ===
    { code: "MATH3401", name: "Analysis I", credits: 6, category: "math-adv-core", prerequisites: ["MATH2211"] },

    // === Advanced Electives — List A ===
    { code: "MATH3301", name: "Algebra I", credits: 6, category: "math-elec-a", prerequisites: ["MATH2101", "MATH2102"] },
    { code: "MATH3403", name: "Functions of a Complex Variable", credits: 6, category: "math-elec-a", prerequisites: ["MATH2211", "MATH2241"] },
    { code: "MATH3601", name: "Numerical Analysis", credits: 6, category: "math-elec-a", prerequisites: ["MATH2101", "MATH2211"] },
    { code: "MATH3603", name: "Probability Theory", credits: 6, category: "math-elec-a", prerequisites: ["MATH2101", "MATH2211"] },
    { code: "MATH3904", name: "Introduction to Optimization", credits: 6, category: "math-elec-a", prerequisites: ["MATH2101", "MATH2211"] },

    // === Advanced Electives — List B ===
    { code: "MATH3002", name: "Mathematics Seminar", credits: 6, category: "math-elec-b", prerequisites: [] },
    { code: "MATH3304", name: "Introduction to Number Theory", credits: 6, category: "math-elec-b", prerequisites: ["MATH2012"] },
    { code: "MATH3405", name: "Differential Equations", credits: 6, category: "math-elec-b", prerequisites: ["MATH2101", "MATH2211"] },
    { code: "MATH3541", name: "Introduction to Topology", credits: 6, category: "math-elec-b", prerequisites: ["MATH2241"] },
    { code: "MATH3600", name: "Discrete Mathematics", credits: 6, category: "math-elec-b", prerequisites: [] },
    { code: "MATH3901", name: "Operations Research I", credits: 6, category: "math-elec-b", prerequisites: ["MATH2101"] },
    { code: "MATH3906", name: "Financial Calculus", credits: 6, category: "math-elec-b", prerequisites: ["MATH2211"] },
    { code: "MATH3911", name: "Game Theory and Strategy", credits: 6, category: "math-elec-b", prerequisites: [] },
    { code: "MATH3943", name: "Network Models in Operations Research", credits: 6, category: "math-elec-b", prerequisites: [] },
    { code: "MATH4302", name: "Algebra II", credits: 6, category: "math-elec-b", prerequisites: ["MATH3301"] },
    { code: "MATH4402", name: "Analysis II", credits: 6, category: "math-elec-b", prerequisites: ["MATH3401"] },
    { code: "MATH4404", name: "Functional Analysis", credits: 6, category: "math-elec-b", prerequisites: ["MATH3401"] },
    { code: "MATH4406", name: "Introduction to Partial Differential Equations", credits: 6, category: "math-elec-b", prerequisites: ["MATH3401"] },
    { code: "MATH4501", name: "Geometry", credits: 6, category: "math-elec-b", prerequisites: ["MATH2101"] },
    { code: "MATH4511", name: "Introduction to Differentiable Manifolds", credits: 6, category: "math-elec-b", prerequisites: ["MATH2211", "MATH2241"] },
    { code: "MATH4602", name: "Scientific Computing", credits: 6, category: "math-elec-b", prerequisites: ["MATH3601"] },
    { code: "MATH4902", name: "Operations Research II", credits: 6, category: "math-elec-b", prerequisites: ["MATH3901"] },
    { code: "MATH4907", name: "Numerical Methods for Financial Calculus", credits: 6, category: "math-elec-b", prerequisites: ["MATH3601"] },

    // === Capstone ===
    { code: "MATH3999", name: "Directed Studies in Mathematics", credits: 6, category: "math-capstone", prerequisites: [] },
    { code: "MATH4910", name: "Senior Mathematics Seminar", credits: 6, category: "math-capstone", prerequisites: [] },
    { code: "MATH4911", name: "Mathematics Capstone Project", credits: 6, category: "math-capstone", prerequisites: [] },
    { code: "MATH4966", name: "Mathematics Internship", credits: 6, category: "math-capstone", prerequisites: [] },
    { code: "MATH4999", name: "Mathematics Project", credits: 12, category: "math-capstone", prerequisites: [] },

    // === Language ===
    { code: "CAES1000", name: "Core University English", credits: 6, category: "language", prerequisites: [] },
    { code: "CAES1001", name: "Academic Communication in English", credits: 0, category: "language", prerequisites: [] },
    { code: "CAES9000", name: "English in the Discipline", credits: 6, category: "language", prerequisites: ["CAES1000"] },
    { code: "CHIN9001", name: "Practical Chinese for Science Students", credits: 6, category: "language", prerequisites: [] },
    { code: "CHIN9002", name: "Chinese for Academic Purposes", credits: 6, category: "language", prerequisites: [] },
    { code: "CHIN9003", name: "Chinese Communication Skills", credits: 6, category: "language", prerequisites: [] },

    // === Common Core ===
    { code: "CCST____", name: "Common Core: Scientific & Technological Literacy", credits: 6, category: "common-core", prerequisites: [] },
    { code: "CCHU____", name: "Common Core: Arts & Humanities", credits: 6, category: "common-core", prerequisites: [] },
    { code: "CCGL____", name: "Common Core: Global Issues", credits: 6, category: "common-core", prerequisites: [] },
    { code: "CCCH____", name: "Common Core: China — Culture, State & Society", credits: 6, category: "common-core", prerequisites: [] },
    { code: "CCAI____", name: "Common Core: Artificial Intelligence", credits: 6, category: "common-core", prerequisites: [] },
    { code: "CC______", name: "Common Core: Additional", credits: 6, category: "common-core", prerequisites: [] },

    // === AI Literacy (AILT) ===
    { code: "AILT1001", name: "AI Literacy I", credits: 6, category: "ai-literacy", prerequisites: [] },
    { code: "AILT1002", name: "AI Literacy II", credits: 6, category: "ai-literacy", prerequisites: [] },

    // === Free Electives — Computer Science ===
    { code: "COMP1117", name: "Computer Programming", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP2113", name: "Programming Technologies", credits: 6, category: "free-elective", prerequisites: ["COMP1117"] },
    { code: "COMP2119", name: "Intro to Data Structures and Algorithms", credits: 6, category: "free-elective", prerequisites: ["COMP1117"] },
    { code: "COMP2120", name: "Computer Organization", credits: 6, category: "free-elective", prerequisites: ["COMP1117"] },
    { code: "COMP2121", name: "Discrete Mathematics (CS)", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP2396", name: "Object-Oriented Programming and Java", credits: 6, category: "free-elective", prerequisites: ["COMP2113"] },
    { code: "COMP2501", name: "Intro to Data Science and Engineering", credits: 6, category: "free-elective", prerequisites: ["COMP1117"] },
    { code: "COMP3230", name: "Principles of Operating Systems", credits: 6, category: "free-elective", prerequisites: ["COMP2119", "COMP2120"] },
    { code: "COMP3234", name: "Computer and Communication Networks", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3251", name: "Algorithm Design", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3252", name: "Algorithm Design and Analysis", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3270", name: "Artificial Intelligence", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3278", name: "Intro to Database Management Systems", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3297", name: "Software Engineering", credits: 6, category: "free-elective", prerequisites: ["COMP2396"] },
    { code: "COMP3314", name: "Introduction to Machine Learning", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3317", name: "Introduction to Computer Vision", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3340", name: "Introduction to Deep Learning", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3353", name: "Bioinformatics", credits: 6, category: "free-elective", prerequisites: ["COMP1117"] },
    { code: "COMP3356", name: "Robotics", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3358", name: "Distributed and Parallel Computing", credits: 6, category: "free-elective", prerequisites: ["COMP3230"] },
    { code: "COMP2118", name: "Data Structures and Algorithms Essentials", credits: 6, category: "free-elective", prerequisites: ["COMP2113"] },
    { code: "COMP3160", name: "Web3.0 for Social Impact", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3231", name: "Computer Architecture", credits: 6, category: "free-elective", prerequisites: ["COMP2120"] },
    { code: "COMP3235", name: "Compiling Techniques", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3258", name: "Functional Programming", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3259", name: "Principles of Programming Languages", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3271", name: "Computer Graphics", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3311", name: "Legal Aspects of Computing", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3316", name: "Quantum Information and Computation", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3320", name: "Electronic Commerce Technology", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3322", name: "Modern Technologies on World Wide Web", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3323", name: "Advanced Database Systems", credits: 6, category: "free-elective", prerequisites: ["COMP3278"] },
    { code: "COMP3329", name: "Computer Game Design and Programming", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3330", name: "Interactive Mobile Application Design and Programming", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3351", name: "Advanced Algorithm Analysis", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3352", name: "Algorithmic Game Theory", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3354", name: "Statistical Learning", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3355", name: "Cyber Security", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3357", name: "Cryptography", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3360", name: "Data-Driven Computer Animation", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3361", name: "Natural Language Processing", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP3362", name: "Hands-on AI: Experimentation and Applications", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3364", name: "Digital Forensics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3365", name: "Cyber Attack and Defense", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3366", name: "Quantum Algorithms and Computer Architecture", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3405", name: "Engineering Quality Software", credits: 6, category: "free-elective", prerequisites: ["COMP2396"] },
    { code: "COMP3407", name: "Scientific Computing", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3412", name: "Internship", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3414", name: "Experiential Learning on AI and Robotics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "COMP3516", name: "Data Analytics for IoT", credits: 6, category: "free-elective", prerequisites: ["COMP2119"] },
    { code: "COMP4510", name: "Principles of Machine Learning", credits: 6, category: "free-elective", prerequisites: ["COMP3314"] },
    { code: "COMP4511", name: "Principles of Deep Learning", credits: 6, category: "free-elective", prerequisites: ["COMP3340"] },
    { code: "COMP4512", name: "Advanced Computer Vision", credits: 6, category: "free-elective", prerequisites: ["COMP3317"] },
    { code: "COMP4801", name: "Final Year Project", credits: 12, category: "free-elective", prerequisites: [] },
    { code: "COMP4805", name: "CS Project (2nd Major)", credits: 6, category: "free-elective", prerequisites: [] },

    // === Free Electives — Economics ===
    { code: "ECON1210", name: "Introductory Microeconomics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ECON1220", name: "Introductory Macroeconomics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ECON1280", name: "Analysis of Economic Data", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ECON2210", name: "Intermediate Microeconomics", credits: 6, category: "free-elective", prerequisites: ["ECON1210"] },
    { code: "ECON2214", name: "Games and Decisions", credits: 6, category: "free-elective", prerequisites: ["ECON1210"] },
    { code: "ECON2220", name: "Intermediate Macroeconomics", credits: 6, category: "free-elective", prerequisites: ["ECON1220"] },
    { code: "ECON2226", name: "Chinese Economy", credits: 6, category: "free-elective", prerequisites: ["ECON1210"] },
    { code: "ECON2253", name: "International Macroeconomics", credits: 6, category: "free-elective", prerequisites: ["ECON1220"] },
    { code: "ECON2252", name: "Theory of International Trade", credits: 6, category: "free-elective", prerequisites: ["ECON1210"] },
    { code: "ECON2262", name: "Economic Development", credits: 6, category: "free-elective", prerequisites: ["ECON1210"] },
    { code: "ECON2280", name: "Introductory Econometrics", credits: 6, category: "free-elective", prerequisites: ["ECON1210"] },
    { code: "ECON3215", name: "Uncertainty and Information", credits: 6, category: "free-elective", prerequisites: ["ECON2210"] },
    { code: "ECON3222", name: "Monetary Economics", credits: 6, category: "free-elective", prerequisites: ["ECON2220"] },
    { code: "ECON3225", name: "Big Data Economics", credits: 6, category: "free-elective", prerequisites: ["ECON2280"] },
    { code: "ECON3234", name: "Behavioural Economics", credits: 6, category: "free-elective", prerequisites: ["ECON2210"] },
    { code: "ECON3284", name: "Causal Inference", credits: 6, category: "free-elective", prerequisites: ["ECON2280"] },
    { code: "ECON4200", name: "Senior Seminar in Economics and Finance", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ECON4211", name: "Advanced Microeconomics", credits: 6, category: "free-elective", prerequisites: ["ECON2210"] },
    { code: "ECON4221", name: "Advanced Macroeconomics", credits: 6, category: "free-elective", prerequisites: ["ECON2220"] },

    // === Free Electives — Finance ===
    { code: "ACCT1101", name: "Introduction to Financial Accounting", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ACCT3114", name: "Valuation Using Financial Statements", credits: 6, category: "free-elective", prerequisites: ["ACCT1101"] },
    { code: "FINA1310", name: "Corporate Finance", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "FINA2311", name: "Case Studies in Corporate Finance", credits: 6, category: "free-elective", prerequisites: ["FINA1310"] },
    { code: "FINA2312", name: "Advanced Corporate Finance", credits: 6, category: "free-elective", prerequisites: ["FINA1310"] },
    { code: "FINA2320", name: "Investments and Portfolio Analysis", credits: 6, category: "free-elective", prerequisites: ["FINA1310"] },
    { code: "FINA2322", name: "Derivatives", credits: 6, category: "free-elective", prerequisites: ["FINA1310"] },
    { code: "FINA2330", name: "Financial Markets and Institutions", credits: 6, category: "free-elective", prerequisites: ["FINA1310"] },
    { code: "FINA2331", name: "Management of Commercial Banks", credits: 6, category: "free-elective", prerequisites: ["FINA1310"] },
    { code: "FINA2342", name: "Insurance: Theory and Practice", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "FINA3337", name: "Venture Capital and Private Equity", credits: 6, category: "free-elective", prerequisites: ["FINA2320"] },
    { code: "FINA3350", name: "Mathematical Finance", credits: 6, category: "free-elective", prerequisites: ["FINA2322"] },
    { code: "FINA3381", name: "Behavioural Finance", credits: 6, category: "free-elective", prerequisites: ["FINA2320"] },
    { code: "FINA2350", name: "Text Analytics and NLP in Finance and Fintech", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "FINA4354", name: "Financial Engineering", credits: 6, category: "free-elective", prerequisites: ["FINA2322"] },

    // === Free Electives — Statistics ===
    { code: "SDST1018", name: "Foundations of Data Science", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "SDST1600", name: "Statistics: Ideas and Concepts", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "SDST2601", name: "Probability and Statistics I", credits: 6, category: "free-elective", prerequisites: ["MATH1013"] },
    { code: "SDST2602", name: "Probability and Statistics II", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST2604", name: "Intro to R/Python Programming and Data Analysis", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "SDST3010", name: "Image Processing and Computer Vision", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3021", name: "Modern Biostatistics", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3600", name: "Linear Statistical Analysis", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3602", name: "Statistical Inference", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3603", name: "Stochastic Processes", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3604", name: "Design and Analysis of Experiments", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3609", name: "The Statistics of Investment Risk", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3610", name: "Risk Management and Insurance", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3612", name: "Statistical Machine Learning", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3613", name: "Marketing Analytics", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3615", name: "Practical Mathematics for Investment", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3617", name: "Sample Survey Methods", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3618", name: "Derivatives and Risk Management", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3620", name: "Modern Nonparametric Statistics", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3621", name: "Statistical Data Analysis", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3622", name: "Data Visualization", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3606", name: "Business Logistics", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3607", name: "Statistics in Clinical Medicine and Bio-medical Research", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3608", name: "Statistical Genetics", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3655", name: "Survival Analysis", credits: 6, category: "free-elective", prerequisites: ["SDST2601"] },
    { code: "SDST3799", name: "Directed Studies in Statistics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "SDST4601", name: "Time-Series Analysis", credits: 6, category: "free-elective", prerequisites: ["SDST3600"] },
    { code: "SDST4602", name: "Multivariate Data Analysis", credits: 6, category: "free-elective", prerequisites: ["SDST3600"] },
    { code: "SDST4603", name: "Current Topics in Risk Management", credits: 6, category: "free-elective", prerequisites: ["SDST3609"] },
    { code: "SDST4606", name: "Risk Management and Basel Accords", credits: 6, category: "free-elective", prerequisites: ["SDST3609"] },
    { code: "SDST4607", name: "Credit Risk Analysis", credits: 6, category: "free-elective", prerequisites: ["SDST3600"] },
    { code: "SDST4608", name: "Market Risk Analysis", credits: 6, category: "free-elective", prerequisites: ["SDST3600"] },
    { code: "SDST4609", name: "Big Data Analytics", credits: 6, category: "free-elective", prerequisites: ["SDST3600"] },
    { code: "SDST4610", name: "Bayesian Learning", credits: 6, category: "free-elective", prerequisites: ["SDST3602"] },
    { code: "SDST4611", name: "High-Dimensional Statistical Learning", credits: 6, category: "free-elective", prerequisites: ["SDST3600"] },
    { code: "SDST4612", name: "Interpretable Machine Learning", credits: 6, category: "free-elective", prerequisites: ["SDST3612"] },
    { code: "SDST4613", name: "Causal Inference", credits: 6, category: "free-elective", prerequisites: ["SDST3600"] },
    { code: "SDST4614", name: "Quantitative Risk Management", credits: 6, category: "free-elective", prerequisites: ["SDST3609"] },
    { code: "SDST4710", name: "Capstone Experience for Statistics Undergraduates", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "SDST4766", name: "Statistics Internship", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "SDST4799", name: "Statistics Project", credits: 12, category: "free-elective", prerequisites: [] },
    { code: "SDST7609", name: "Research Methods in Statistics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "SDST7610", name: "Advanced Probability", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "SDST3910", name: "Financial Economics I", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "SDST3911", name: "Financial Economics II", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "SDST4011", name: "Natural Language Processing", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "SDST4023", name: "Medical Image Analysis", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "MATH3900", name: "Optimization for AI and Data Analytics", credits: 6, category: "free-elective", prerequisites: [] },

    // === Free Electives — Physics ===
    { code: "PHYS1150", name: "Problem Solving in Physics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS1250", name: "Fundamental Physics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS2055", name: "Introductory Relativity", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS2150", name: "Methods in Physics I", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS2155", name: "Methods in Physics II", credits: 6, category: "free-elective", prerequisites: ["PHYS2150"] },
    { code: "PHYS2160", name: "Introductory Computational Physics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS2250", name: "Introductory Mechanics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS2255", name: "Introductory Electricity and Magnetism", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS2261", name: "Introductory Heat and Thermodynamics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS2265", name: "Introductory Quantum Physics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS3150", name: "Theoretical Physics", credits: 6, category: "free-elective", prerequisites: ["PHYS2150"] },
    { code: "PHYS3151", name: "Machine Learning in Physics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS3350", name: "Classical Mechanics", credits: 6, category: "free-elective", prerequisites: ["PHYS2150", "PHYS2250"] },
    { code: "PHYS3351", name: "Quantum Mechanics", credits: 6, category: "free-elective", prerequisites: ["PHYS2150", "PHYS2265"] },
    { code: "PHYS3450", name: "Electromagnetism", credits: 6, category: "free-elective", prerequisites: ["PHYS2150", "PHYS2255"] },
    { code: "PHYS3550", name: "Statistical Mechanics and Thermodynamics", credits: 6, category: "free-elective", prerequisites: ["PHYS2150", "PHYS2261"] },
    { code: "PHYS3653", name: "Astrophysics", credits: 6, category: "free-elective", prerequisites: ["PHYS2250"] },
    { code: "PHYS3760", name: "Physics Laboratory", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS3850", name: "Physical Optics", credits: 6, category: "free-elective", prerequisites: ["PHYS2250", "PHYS2255"] },
    { code: "PHYS3851", name: "Atomic and Nuclear Physics", credits: 6, category: "free-elective", prerequisites: ["PHYS2265"] },
    { code: "PHYS3650", name: "Observational Astronomy", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS3660", name: "Astronomy Laboratory", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS3999", name: "Directed Studies in Physics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS4150", name: "Computational Physics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS4151", name: "Data Analysis and Modeling in Physics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS4351", name: "Advanced Quantum Mechanics", credits: 6, category: "free-elective", prerequisites: ["PHYS3150", "PHYS3351"] },
    { code: "PHYS4450", name: "Advanced Electromagnetism", credits: 6, category: "free-elective", prerequisites: ["PHYS3150", "PHYS3450"] },
    { code: "PHYS4550", name: "Advanced Statistical Mechanics", credits: 6, category: "free-elective", prerequisites: ["PHYS3550"] },
    { code: "PHYS4551", name: "Solid State Physics", credits: 6, category: "free-elective", prerequisites: ["PHYS3351"] },
    { code: "PHYS4650", name: "Stellar Physics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS4652", name: "Planetary Science", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS4653", name: "Selected Topics in Astrophysics and Cosmology", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS4654", name: "General Relativity", credits: 6, category: "free-elective", prerequisites: ["PHYS2055", "PHYS3350"] },
    { code: "PHYS4655", name: "Interstellar Medium", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS4656", name: "Advanced Astrophysics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS4850", name: "Particle Physics", credits: 6, category: "free-elective", prerequisites: ["PHYS3351"] },
    { code: "PHYS4966", name: "Physics Internship", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "PHYS4999", name: "Physics Project", credits: 12, category: "free-elective", prerequisites: [] },
    { code: "PHYS7350", name: "Graduate Classical Mechanics", credits: 6, category: "free-elective", prerequisites: ["PHYS3350"] },
    { code: "PHYS7351", name: "Graduate Quantum Mechanics", credits: 6, category: "free-elective", prerequisites: ["PHYS3351"] },
    { code: "PHYS7450", name: "Graduate Electromagnetic Field Theory", credits: 6, category: "free-elective", prerequisites: ["PHYS3450"] },
    { code: "PHYS7550", name: "Graduate Statistical Mechanics", credits: 6, category: "free-elective", prerequisites: ["PHYS3550"] },
    { code: "PHYS7750", name: "Physics of Nanoelectronics", credits: 6, category: "free-elective", prerequisites: [] },

    // === Free Electives — Electrical & Electronic Engineering ===
    { code: "ENGG1310", name: "Electricity and Electronics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC2147", name: "Electrical Energy Technology", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC2243", name: "Introduction to Electricity and Magnetism", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC2245", name: "Control Systems I", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC2346", name: "Electric Circuit Theory", credits: 6, category: "free-elective", prerequisites: ["ENGG1310"] },
    { code: "ELEC2347", name: "Fundamentals of Optics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC2441", name: "Computer Organization and Microprocessors", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC2543", name: "Object-Oriented Programming and Data Structures", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC2544", name: "Introduction to Electronic Commerce and Financial Technology", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3142", name: "Electrical Energy Conversion", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3143", name: "Power Electronics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3241", name: "Signals and Linear Systems", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3243", name: "Fundamentals of Next-Generation Communications", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3244", name: "Digital Signal Processing", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3248", name: "Engineering Electromagnetism and Antenna Design", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3249", name: "Pattern Recognition and Machine Intelligence", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3342", name: "Digital System Design", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3347", name: "Electronic Materials and Quantum Physics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3349", name: "Optical Devices", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3350", name: "Electronic Circuits and Devices I", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3351", name: "Electronic Circuits and Devices II", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3441", name: "Computer Architecture", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3443", name: "Computer Networks", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3543", name: "Advanced Systems Programming", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3544", name: "Introduction to Data Analytics", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC3641", name: "Human Computer Interaction", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC4343", name: "Design of Digital Integrated Circuits", credits: 6, category: "free-elective", prerequisites: [] },
    { code: "ELEC4344", name: "Advanced Electronic Circuits", credits: 6, category: "free-elective", prerequisites: [] },
];

// Category display names
const CATEGORY_NAMES = {
    "math-core": "Math Core",
    "math-adv-core": "Advanced Core",
    "math-elec-a": "Elective List A",
    "math-elec-b": "Elective List B",
    "math-capstone": "Capstone",
    "science": "Science Foundation",
    "common-core": "Common Core",
    "language": "Language",
    "ai-literacy": "AI Literacy",
    "second-major": "2nd Major / Minor",
    "free-elective": "Free Elective"
};

// Semester availability: 1 = Sem 1 only, 2 = Sem 2 only, 3 = both semesters, 0 = full year / TBD
const COURSE_SEMESTERS = {
    // Science Foundation
    "SCNC1111": 1, "SCNC1112": 2,
    // MATH (per 2024-25 Advice on Course Selection, HKU Math Dept)
    // Intro / Core
    "MATH1013": 3, "MATH2012": 3, "MATH2014": 3,
    "MATH2101": 3, "MATH2102": 2, "MATH2211": 3, "MATH2241": 3,
    "MATH2301": 0,
    // Advanced — Algebra / Number Theory
    "MATH3301": 1, "MATH3303": 2, "MATH3304": 2, "MATH4302": 2,
    // Advanced — Analysis
    "MATH3401": 1, "MATH3403": 2, "MATH3405": 2, "MATH3406": 1, "MATH3407": 2, "MATH3408": 1,
    "MATH4402": 2, "MATH4404": 1, "MATH4406": 1, "MATH4511": 2,
    // Advanced — Topology / Geometry / Discrete
    "MATH3501": 1, "MATH3502": 2, "MATH3504": 2, "MATH3541": 1, "MATH3600": 1,
    // Advanced — Computational / Numerical
    "MATH3601": 2, "MATH4501": 0, "MATH4602": 2,
    // Advanced — Probability / Statistics
    "MATH3603": 2,
    // Advanced — Optimization / OR / Finance
    "MATH3900": 1, "MATH3901": 2, "MATH3904": 1, "MATH3905": 1, "MATH3906": 2,
    "MATH3911": 2, "MATH3943": 1,
    // Seminar / Capstone / Project
    "MATH3002": 2, "MATH3999": 3, "MATH4902": 0, "MATH4907": 0,
    "MATH4910": 2, "MATH4911": 0, "MATH4966": 3, "MATH4999": 0,
    // Language
    "CAES1000": 1, "CAES1001": 0, "CAES9000": 2,
    "CHIN9001": 3, "CHIN9002": 3, "CHIN9003": 3,
    "AILT1001": 1, "AILT1002": 2,
    // CS
    "COMP1117": 3, "COMP2113": 3, "COMP2118": 0, "COMP2119": 3,
    "COMP2120": 2, "COMP2121": 3, "COMP2501": 3,
    "COMP3230": 1, "COMP3234": 3, "COMP3251": 2, "COMP3252": 2,
    "COMP3258": 2, "COMP3259": 2, "COMP3270": 3, "COMP3271": 1,
    "COMP3278": 3, "COMP3297": 3, "COMP3311": 0, "COMP3314": 3,
    "COMP3316": 1, "COMP3317": 2, "COMP3320": 0, "COMP3322": 3,
    "COMP3323": 2, "COMP3329": 2, "COMP3330": 1, "COMP3340": 2,
    "COMP3351": 0, "COMP3352": 0, "COMP3353": 1, "COMP3354": 1,
    "COMP3355": 1, "COMP3356": 1, "COMP3357": 1, "COMP3358": 2,
    "COMP3360": 2, "COMP3361": 2, "COMP3362": 0, "COMP3364": 0,
    "COMP3365": 2, "COMP3366": 1, "COMP3405": 0, "COMP3407": 0,
    "COMP3412": 0, "COMP3414": 0, "COMP3516": 2,
    "COMP4510": 0, "COMP4511": 0, "COMP4512": 0, "COMP4801": 0,
    "COMP3160": 0,
    // Physics
    "PHYS1150": 3, "PHYS1250": 3, "PHYS2055": 2, "PHYS2150": 1,
    "PHYS2155": 2, "PHYS2160": 0, "PHYS2250": 3, "PHYS2255": 2,
    "PHYS2261": 1, "PHYS2265": 3, "PHYS3150": 1, "PHYS3151": 0,
    "PHYS3350": 2, "PHYS3351": 1, "PHYS3450": 2, "PHYS3550": 1,
    "PHYS3650": 1, "PHYS3653": 2, "PHYS3660": 1, "PHYS3750": 1,
    "PHYS3760": 2, "PHYS3850": 2, "PHYS3851": 2,
    "PHYS4150": 1, "PHYS4151": 0, "PHYS4351": 2, "PHYS4450": 1,
    "PHYS4550": 0, "PHYS4551": 1, "PHYS4650": 0, "PHYS4652": 2,
    "PHYS4653": 1, "PHYS4654": 1, "PHYS4655": 0, "PHYS4656": 2,
    "PHYS4850": 1, "PHYS4966": 0, "PHYS4999": 0,
    "PHYS7350": 0, "PHYS7351": 1, "PHYS7450": 2, "PHYS7550": 2, "PHYS7750": 0,
    // SDST (Statistics / Data Science)
    "SDST1018": 2, "SDST1600": 3, "SDST2601": 3, "SDST2602": 3, "SDST2604": 1,
    "SDST3010": 2, "SDST3021": 1, "SDST3600": 3, "SDST3602": 1, "SDST3603": 1,
    "SDST3604": 0, "SDST3606": 1, "SDST3607": 0, "SDST3608": 0,
    "SDST3609": 1, "SDST3610": 2, "SDST3612": 3, "SDST3613": 1,
    "SDST3615": 2, "SDST3617": 2, "SDST3618": 2, "SDST3620": 1,
    "SDST3621": 2, "SDST3622": 2, "SDST3655": 2, "SDST3799": 3,
    "SDST3910": 1, "SDST3911": 2, "SDST4011": 1, "SDST4023": 0,
    "SDST4601": 1, "SDST4602": 2, "SDST4603": 1, "SDST4606": 0,
    "SDST4607": 2, "SDST4608": 2, "SDST4609": 2, "SDST4610": 1,
    "SDST4611": 0, "SDST4612": 0, "SDST4613": 0, "SDST4614": 0,
    "SDST4710": 3, "SDST4766": 3, "SDST4799": 0, "SDST7609": 1, "SDST7610": 2,
    // Economics
    "ECON1210": 3, "ECON1220": 3, "ECON1280": 3, "ECON2210": 3, "ECON2220": 3,
    "ECON2252": 1, "ECON2280": 3, "ECON3284": 2, "ECON4200": 0,
    "ECON4211": 1, "ECON4221": 1,
    // Finance / Accounting
    "ACCT1101": 3, "ACCT3114": 2, "FINA1310": 3, "FINA2320": 3,
    "FINA2322": 3, "FINA2330": 3, "FINA2331": 0, "FINA2342": 3, "FINA2350": 2,
    // EEE
    "ENGG1310": 3, "ELEC2147": 2, "ELEC2243": 1, "ELEC2245": 1,
    "ELEC2346": 1, "ELEC2347": 1, "ELEC2441": 1, "ELEC2543": 2,
    "ELEC2544": 2, "ELEC3142": 2, "ELEC3143": 1, "ELEC3241": 2,
    "ELEC3243": 1, "ELEC3244": 2, "ELEC3248": 2, "ELEC3249": 2,
    "ELEC3342": 1, "ELEC3347": 1, "ELEC3349": 1, "ELEC3350": 2,
    "ELEC3351": 2, "ELEC3441": 2, "ELEC3443": 3, "ELEC3543": 1,
    "ELEC3544": 2, "ELEC3641": 2, "ELEC4343": 1, "ELEC4344": 2,
};

// ==================== Second Major / Minor Presets ====================
const PROGRAM_PRESETS = {

    // ==================== DOUBLE MAJOR OPTIONS ====================

    "cs-major": {
        name: "Computer Science",
        type: "double",
        credits: 96,
        overlapNote: "MATH3600 can substitute COMP2121. MATH2012/MATH2014/SDST2601 overlap — take replacement electives. Max 24cr overlap for double major.",
        courses: [
            // Core Introductory (48 cr)
            { code: "COMP1117", name: "Computer Programming", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP2113", name: "Programming Technologies", credits: 6, category: "second-major", prerequisites: ["COMP1117"] },
            { code: "COMP2119", name: "Intro to Data Structures and Algorithms", credits: 6, category: "second-major", prerequisites: ["COMP2113"] },
            { code: "COMP2120", name: "Computer Organization", credits: 6, category: "second-major", prerequisites: ["COMP1117"] },
            { code: "COMP2121", name: "Discrete Mathematics (CS)", credits: 6, category: "second-major", prerequisites: [] },
            // Core Advanced (12 cr)
            { code: "COMP3230", name: "Principles of Operating Systems", credits: 6, category: "second-major", prerequisites: ["COMP2119", "COMP2120"] },
            { code: "COMP3314", name: "Introduction to Machine Learning", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            // Electives
            { code: "COMP2396", name: "Object-Oriented Programming and Java", credits: 6, category: "second-major", prerequisites: ["COMP2113"] },
            { code: "COMP2501", name: "Intro to Data Science and Engineering", credits: 6, category: "second-major", prerequisites: ["COMP1117"] },
            { code: "COMP3234", name: "Computer and Communication Networks", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3251", name: "Algorithm Design", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3252", name: "Algorithm Design and Analysis", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3270", name: "Introduction to Artificial Intelligence", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3278", name: "Intro to Database Management Systems", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3297", name: "Software Engineering", credits: 6, category: "second-major", prerequisites: ["COMP2113"] },
            { code: "COMP3317", name: "Introduction to Computer Vision", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3340", name: "Introduction to Deep Learning", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3231", name: "Computer Architecture", credits: 6, category: "second-major", prerequisites: ["COMP2120"] },
            { code: "COMP3235", name: "Compiling Techniques", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3258", name: "Functional Programming", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3259", name: "Principles of Programming Languages", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3271", name: "Computer Graphics", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3316", name: "Quantum Information and Computation", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP3322", name: "Modern Technologies on World Wide Web", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP3323", name: "Advanced Database Systems", credits: 6, category: "second-major", prerequisites: ["COMP3278"] },
            { code: "COMP3329", name: "Computer Game Design and Programming", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP3330", name: "Interactive Mobile Application Design and Programming", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP3351", name: "Advanced Algorithm Analysis", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3352", name: "Algorithmic Game Theory", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3353", name: "Bioinformatics", credits: 6, category: "second-major", prerequisites: ["COMP1117"] },
            { code: "COMP3354", name: "Statistical Learning", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3355", name: "Cyber Security", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP3356", name: "Robotics", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3357", name: "Cryptography", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3358", name: "Distributed and Parallel Computing", credits: 6, category: "second-major", prerequisites: ["COMP3230"] },
            { code: "COMP3360", name: "Data-Driven Computer Animation", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3361", name: "Natural Language Processing", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3362", name: "Hands-on AI: Experimentation and Applications", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP3364", name: "Digital Forensics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP3365", name: "Cyber Attack and Defense", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP3366", name: "Quantum Algorithms and Computer Architecture", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP3405", name: "Engineering Quality Software", credits: 6, category: "second-major", prerequisites: ["COMP2396"] },
            { code: "COMP3407", name: "Scientific Computing", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP3516", name: "Data Analytics for IoT", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP4510", name: "Principles of Machine Learning", credits: 6, category: "second-major", prerequisites: ["COMP3314"] },
            { code: "COMP4511", name: "Principles of Deep Learning", credits: 6, category: "second-major", prerequisites: ["COMP3340"] },
            { code: "COMP4512", name: "Advanced Computer Vision", credits: 6, category: "second-major", prerequisites: ["COMP3317"] },
            // Capstone
            { code: "COMP4801", name: "Final Year Project", credits: 12, category: "second-major", prerequisites: [] },
        ]
    },

    "econ-major": {
        name: "Economics",
        type: "double",
        credits: 72,
        overlapNote: "Faculty Core (24cr) can be double-counted in major-major. MATH1013 overlaps with Math major. Capstone: ECON4200.",
        courses: [
            // Faculty Core (24 cr)
            { code: "ACCT1101", name: "Introduction to Financial Accounting", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ECON1210", name: "Introductory Microeconomics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "FINA1310", name: "Corporate Finance", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ECON1280", name: "Analysis of Economic Data", credits: 6, category: "second-major", prerequisites: [] },
            // Disciplinary Core (30 cr)
            { code: "ECON1220", name: "Introductory Macroeconomics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ECON2210", name: "Intermediate Microeconomics", credits: 6, category: "second-major", prerequisites: ["ECON1210"] },
            { code: "ECON2220", name: "Intermediate Macroeconomics", credits: 6, category: "second-major", prerequisites: ["ECON1220"] },
            { code: "ECON2280", name: "Introductory Econometrics", credits: 6, category: "second-major", prerequisites: ["ECON1210"] },
            // Electives
            { code: "ECON2214", name: "Games and Decisions", credits: 6, category: "second-major", prerequisites: ["ECON1210"] },
            { code: "ECON2226", name: "Chinese Economy", credits: 6, category: "second-major", prerequisites: ["ECON1210"] },
            { code: "ECON2252", name: "Theory of International Trade", credits: 6, category: "second-major", prerequisites: ["ECON1210"] },
            { code: "ECON3222", name: "Monetary Economics", credits: 6, category: "second-major", prerequisites: ["ECON2220"] },
            { code: "ECON3225", name: "Big Data Economics", credits: 6, category: "second-major", prerequisites: ["ECON2280"] },
            { code: "ECON3234", name: "Behavioural Economics", credits: 6, category: "second-major", prerequisites: ["ECON2210"] },
            { code: "ECON3284", name: "Causal Inference", credits: 6, category: "second-major", prerequisites: ["ECON2280"] },
            { code: "ECON4211", name: "Advanced Microeconomics", credits: 6, category: "second-major", prerequisites: ["ECON2210"] },
            { code: "ECON4221", name: "Advanced Macroeconomics", credits: 6, category: "second-major", prerequisites: ["ECON2220"] },
            // Capstone
            { code: "ECON4200", name: "Senior Seminar in Economics and Finance", credits: 6, category: "second-major", prerequisites: [] },
        ]
    },

    "fina-major": {
        name: "Finance",
        type: "double",
        credits: 78,
        overlapNote: "Faculty Core (24cr) can be double-counted in major-major. MATH1013 overlaps with Math major. Capstone: ECON4200.",
        courses: [
            // Faculty Core (24 cr)
            { code: "ACCT1101", name: "Introduction to Financial Accounting", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ECON1210", name: "Introductory Microeconomics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "FINA1310", name: "Corporate Finance", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ECON1280", name: "Analysis of Economic Data", credits: 6, category: "second-major", prerequisites: [] },
            // Disciplinary Core (36 cr)
            { code: "ECON1220", name: "Introductory Macroeconomics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ECON2280", name: "Introductory Econometrics", credits: 6, category: "second-major", prerequisites: ["ECON1210"] },
            { code: "FINA2320", name: "Investments and Portfolio Analysis", credits: 6, category: "second-major", prerequisites: ["FINA1310"] },
            { code: "FINA2322", name: "Derivatives", credits: 6, category: "second-major", prerequisites: ["FINA1310"] },
            // Electives (18 cr)
            { code: "FINA2311", name: "Case Studies in Corporate Finance", credits: 6, category: "second-major", prerequisites: ["FINA1310"] },
            { code: "FINA2312", name: "Advanced Corporate Finance", credits: 6, category: "second-major", prerequisites: ["FINA1310"] },
            { code: "FINA2330", name: "Financial Markets and Institutions", credits: 6, category: "second-major", prerequisites: ["FINA1310"] },
            { code: "FINA3337", name: "Venture Capital and Private Equity", credits: 6, category: "second-major", prerequisites: ["FINA2320"] },
            { code: "FINA3350", name: "Mathematical Finance", credits: 6, category: "second-major", prerequisites: ["FINA2322"] },
            { code: "FINA3381", name: "Behavioural Finance", credits: 6, category: "second-major", prerequisites: ["FINA2320"] },
            { code: "FINA4354", name: "Financial Engineering", credits: 6, category: "second-major", prerequisites: ["FINA2322"] },
            { code: "FINA2350", name: "Text Analytics and NLP in Finance and Fintech", credits: 6, category: "second-major", prerequisites: [] },
            // Capstone
            { code: "ECON4200", name: "Senior Seminar in Economics and Finance", credits: 6, category: "second-major", prerequisites: [] },
        ]
    },

    "stat-major": {
        name: "Statistics",
        type: "double",
        credits: 96,
        overlapNote: "Statistics 2nd Major (2025-26): 96 cr total. MATH1013 & MATH2014 overlap with Math major — no double counting. If MATH2014 already taken, replace with MATH2101 + MATH2211. Cannot combine with Decision Analytics, Risk Management, or Stat/RM Minor.",
        courses: [
            // Introductory Core (30 cr)
            { code: "MATH1013", name: "University Mathematics II", credits: 6, category: "second-major", prerequisites: [] },
            { code: "MATH2014", name: "Multivariable Calculus and Linear Algebra", credits: 6, category: "second-major", prerequisites: ["MATH1013"] },
            { code: "SDST1600", name: "Statistics: Ideas and Concepts", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST2601", name: "Probability and Statistics I", credits: 6, category: "second-major", prerequisites: ["MATH1013"] },
            { code: "SDST2602", name: "Probability and Statistics II", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            // Advanced Core (42 cr)
            { code: "SDST3600", name: "Linear Statistical Analysis", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3602", name: "Statistical Inference", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3603", name: "Stochastic Processes", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3620", name: "Modern Nonparametric Statistics", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3621", name: "Statistical Data Analysis", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST4602", name: "Multivariate Data Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST4610", name: "Bayesian Learning", credits: 6, category: "second-major", prerequisites: ["SDST3602"] },
            // Advanced Electives — List S1 (6+ cr)
            { code: "SDST3612", name: "Statistical Machine Learning", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3655", name: "Survival Analysis", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST4601", name: "Time-Series Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            // Advanced Electives — List S2 (12+ cr)
            { code: "SDST3021", name: "Modern Biostatistics", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3604", name: "Design and Analysis of Experiments", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3606", name: "Business Logistics", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3607", name: "Statistics in Clinical Medicine and Bio-medical Research", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3608", name: "Statistical Genetics", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3613", name: "Marketing Analytics", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3617", name: "Sample Survey Methods", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST4611", name: "High-Dimensional Statistical Learning", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST4613", name: "Causal Inference", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST7609", name: "Research Methods in Statistics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST7610", name: "Advanced Probability", credits: 6, category: "second-major", prerequisites: [] },
            // Capstone (6 cr)
            { code: "SDST3799", name: "Directed Studies in Statistics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4710", name: "Capstone Experience for Statistics Undergraduates", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4766", name: "Statistics Internship", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4799", name: "Statistics Project", credits: 12, category: "second-major", prerequisites: [] },
        ]
    },

    "rm-major": {
        name: "Risk Management",
        type: "double",
        credits: 90,
        overlapNote: "Risk Management 2nd Major (2025-26): 90 cr total. MATH1013 & MATH2014 overlap with Math major — no double counting; take replacement electives. If MATH2014 already taken, replace with MATH2101 + MATH2211. Cannot combine with Statistics or Decision Analytics major.",
        courses: [
            // Introductory Core (30 cr)
            { code: "MATH1013", name: "University Mathematics II", credits: 6, category: "second-major", prerequisites: [] },
            { code: "MATH2014", name: "Multivariable Calculus and Linear Algebra", credits: 6, category: "second-major", prerequisites: ["MATH1013"] },
            { code: "SDST1600", name: "Statistics: Ideas and Concepts", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST2601", name: "Probability and Statistics I", credits: 6, category: "second-major", prerequisites: ["MATH1013"] },
            { code: "SDST2602", name: "Probability and Statistics II", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            // Advanced Core (42 cr)
            { code: "SDST3600", name: "Linear Statistical Analysis", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3609", name: "The Statistics of Investment Risk", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3615", name: "Practical Mathematics for Investment", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3618", name: "Derivatives and Risk Management", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST4601", name: "Time-Series Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST4607", name: "Credit Risk Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST4608", name: "Market Risk Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            // Advanced Electives — List R (12+ cr)
            { code: "SDST3602", name: "Statistical Inference", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3603", name: "Stochastic Processes", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3610", name: "Risk Management and Insurance", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3612", name: "Statistical Machine Learning", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3655", name: "Survival Analysis", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3910", name: "Financial Economics I", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST3911", name: "Financial Economics II", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4603", name: "Current Topics in Risk Management", credits: 6, category: "second-major", prerequisites: ["SDST3609"] },
            { code: "SDST4606", name: "Risk Management and Basel Accords in Banking and Finance", credits: 6, category: "second-major", prerequisites: ["SDST3609"] },
            { code: "SDST4610", name: "Bayesian Learning", credits: 6, category: "second-major", prerequisites: ["SDST3602"] },
            { code: "SDST4614", name: "Quantitative Risk Management", credits: 6, category: "second-major", prerequisites: ["SDST3609"] },
            // Capstone (6 cr)
            { code: "SDST3799", name: "Directed Studies in Statistics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4710", name: "Capstone Experience for Statistics Undergraduates", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4766", name: "Statistics Internship", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4799", name: "Statistics Project", credits: 12, category: "second-major", prerequisites: [] },
        ]
    },

    "da-major": {
        name: "Decision Analytics",
        type: "double",
        credits: 96,
        overlapNote: "Decision Analytics 2nd Major (2025-26): 96 cr total. MATH1013 & MATH2014 overlap with Math major — no double counting. If MATH2014 already taken, replace with MATH2101 + MATH2211. Cannot combine with Statistics or Risk Management.",
        courses: [
            // Introductory Core (48 cr)
            { code: "COMP1117", name: "Computer Programming", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP2113", name: "Programming Technologies", credits: 6, category: "second-major", prerequisites: ["COMP1117"] },
            { code: "COMP2118", name: "Data Structures and Algorithms Essentials", credits: 6, category: "second-major", prerequisites: ["COMP1117"] },
            { code: "MATH1013", name: "University Mathematics II", credits: 6, category: "second-major", prerequisites: [] },
            { code: "MATH2014", name: "Multivariable Calculus and Linear Algebra", credits: 6, category: "second-major", prerequisites: ["MATH1013"] },
            { code: "SDST1600", name: "Statistics: Ideas and Concepts", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST2601", name: "Probability and Statistics I", credits: 6, category: "second-major", prerequisites: ["MATH1013"] },
            { code: "SDST2602", name: "Probability and Statistics II", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            // Advanced Core (30 cr)
            { code: "MATH3900", name: "Optimization for AI and Data Analytics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST3600", name: "Linear Statistical Analysis", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3612", name: "Statistical Machine Learning", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST4609", name: "Big Data Analytics", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST4611", name: "High-Dimensional Statistical Learning", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            // Advanced Electives — List D (12+ cr)
            { code: "COMP3251", name: "Algorithm Design", credits: 6, category: "second-major", prerequisites: ["COMP2118"] },
            { code: "COMP3252", name: "Algorithm Design and Analysis", credits: 6, category: "second-major", prerequisites: ["COMP2118"] },
            { code: "COMP3278", name: "Intro to Database Management Systems", credits: 6, category: "second-major", prerequisites: ["COMP2118"] },
            { code: "COMP3407", name: "Scientific Computing", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST3620", name: "Modern Nonparametric Statistics", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3621", name: "Statistical Data Analysis", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3622", name: "Data Visualization", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST4011", name: "Natural Language Processing", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4023", name: "Medical Image Analysis", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4601", name: "Time-Series Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST4602", name: "Multivariate Data Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST4610", name: "Bayesian Learning", credits: 6, category: "second-major", prerequisites: ["SDST3602"] },
            // Capstone (6 cr)
            { code: "SDST3799", name: "Directed Studies in Statistics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4710", name: "Capstone Experience for Statistics Undergraduates", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4766", name: "Statistics Internship", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST4799", name: "Statistics Project", credits: 12, category: "second-major", prerequisites: [] },
        ]
    },

    "phys-major": {
        name: "Physics",
        type: "double",
        credits: 96,
        overlapNote: "SCNC1111/1112 overlap with Math major (max 24cr double-count). Requires HKDSE Physics Level 3+.",
        courses: [
            // Introductory Core (24 cr)
            { code: "PHYS2250", name: "Introductory Mechanics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS2255", name: "Introductory Electricity and Magnetism", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS2261", name: "Introductory Heat and Thermodynamics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS2265", name: "Introductory Quantum Physics", credits: 6, category: "second-major", prerequisites: [] },
            // Introductory Electives (12 cr min)
            { code: "PHYS1150", name: "Problem Solving in Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS2055", name: "Introductory Relativity", credits: 6, category: "second-major", prerequisites: ["PHYS1150"] },
            { code: "PHYS2150", name: "Methods in Physics I", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS2155", name: "Methods in Physics II", credits: 6, category: "second-major", prerequisites: ["PHYS2150"] },
            { code: "PHYS2160", name: "Introductory Computational Physics", credits: 6, category: "second-major", prerequisites: [] },
            // Advanced Core — List A (24 cr min)
            { code: "PHYS3150", name: "Theoretical Physics", credits: 6, category: "second-major", prerequisites: ["PHYS2150"] },
            { code: "PHYS3350", name: "Classical Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS2150", "PHYS2250"] },
            { code: "PHYS3351", name: "Quantum Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS2150", "PHYS2265"] },
            { code: "PHYS3450", name: "Electromagnetism", credits: 6, category: "second-major", prerequisites: ["PHYS2150", "PHYS2255"] },
            { code: "PHYS3550", name: "Statistical Mechanics and Thermodynamics", credits: 6, category: "second-major", prerequisites: ["PHYS2150", "PHYS2261"] },
            { code: "PHYS3760", name: "Physics Laboratory", credits: 6, category: "second-major", prerequisites: [] },
            // Advanced Electives — List B
            { code: "PHYS3151", name: "Machine Learning in Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS3650", name: "Observational Astronomy", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS3653", name: "Astrophysics", credits: 6, category: "second-major", prerequisites: ["PHYS2250"] },
            { code: "PHYS3660", name: "Astronomy Laboratory", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS3750", name: "Foundations of Laser and Spectroscopy", credits: 6, category: "second-major", prerequisites: ["PHYS2255"] },
            { code: "PHYS3850", name: "Physical Optics", credits: 6, category: "second-major", prerequisites: ["PHYS2250", "PHYS2255"] },
            { code: "PHYS3851", name: "Atomic and Nuclear Physics", credits: 6, category: "second-major", prerequisites: ["PHYS2265"] },
            { code: "PHYS4150", name: "Computational Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4151", name: "Data Analysis and Modeling in Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4351", name: "Advanced Quantum Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS3150", "PHYS3351"] },
            { code: "PHYS4450", name: "Advanced Electromagnetism", credits: 6, category: "second-major", prerequisites: ["PHYS3150", "PHYS3450"] },
            { code: "PHYS4550", name: "Advanced Statistical Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS3550"] },
            { code: "PHYS4551", name: "Solid State Physics", credits: 6, category: "second-major", prerequisites: ["PHYS3351"] },
            { code: "PHYS4650", name: "Stellar Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4652", name: "Planetary Science", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4653", name: "Selected Topics in Astrophysics and Cosmology", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4654", name: "General Relativity", credits: 6, category: "second-major", prerequisites: ["PHYS2055", "PHYS3350"] },
            { code: "PHYS4655", name: "Interstellar Medium", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4656", name: "Advanced Astrophysics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4850", name: "Particle Physics", credits: 6, category: "second-major", prerequisites: ["PHYS3351"] },
            // Capstone
            { code: "PHYS3999", name: "Directed Studies in Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4966", name: "Physics Internship", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4999", name: "Physics Project", credits: 12, category: "second-major", prerequisites: [] },
            // Graduate courses (available to undergrads)
            { code: "PHYS7350", name: "Graduate Classical Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS3350"] },
            { code: "PHYS7351", name: "Graduate Quantum Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS3351"] },
            { code: "PHYS7450", name: "Graduate Electromagnetic Field Theory", credits: 6, category: "second-major", prerequisites: ["PHYS3450"] },
            { code: "PHYS7550", name: "Graduate Statistical Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS3550"] },
            { code: "PHYS7750", name: "Physics of Nanoelectronics", credits: 6, category: "second-major", prerequisites: [] },
        ]
    },

    // ==================== MINOR OPTIONS ====================

    "cs-minor": {
        name: "Computer Science",
        type: "minor",
        credits: 42,
        overlapNote: "No double-counting between major and minor. If a course overlaps, take a replacement elective.",
        courses: [
            // Core (18 cr)
            { code: "COMP1117", name: "Computer Programming", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP2113", name: "Programming Technologies", credits: 6, category: "second-major", prerequisites: ["COMP1117"] },
            { code: "COMP2118", name: "Data Structures and Algorithms Essentials", credits: 6, category: "second-major", prerequisites: ["COMP2113"] },
            // Introductory Electives
            { code: "COMP2120", name: "Computer Organization", credits: 6, category: "second-major", prerequisites: ["COMP1117"] },
            { code: "COMP2121", name: "Discrete Mathematics (CS)", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP2396", name: "Object-Oriented Programming and Java", credits: 6, category: "second-major", prerequisites: ["COMP2113"] },
            { code: "COMP2501", name: "Intro to Data Science and Engineering", credits: 6, category: "second-major", prerequisites: ["COMP1117"] },
            // Advanced Electives
            { code: "COMP3230", name: "Principles of Operating Systems", credits: 6, category: "second-major", prerequisites: ["COMP2119", "COMP2120"] },
            { code: "COMP3234", name: "Computer and Communication Networks", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3251", name: "Algorithm Design", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3270", name: "Introduction to Artificial Intelligence", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3278", name: "Intro to Database Management Systems", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3297", name: "Software Engineering", credits: 6, category: "second-major", prerequisites: ["COMP2113"] },
            { code: "COMP3314", name: "Introduction to Machine Learning", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3317", name: "Introduction to Computer Vision", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3340", name: "Introduction to Deep Learning", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3353", name: "Bioinformatics", credits: 6, category: "second-major", prerequisites: ["COMP1117"] },
            { code: "COMP3356", name: "Robotics", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3355", name: "Cyber Security", credits: 6, category: "second-major", prerequisites: [] },
            { code: "COMP3357", name: "Cryptography", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP3358", name: "Distributed and Parallel Computing", credits: 6, category: "second-major", prerequisites: ["COMP3230"] },
            { code: "COMP3361", name: "Natural Language Processing", credits: 6, category: "second-major", prerequisites: ["COMP2119"] },
            { code: "COMP4510", name: "Principles of Machine Learning", credits: 6, category: "second-major", prerequisites: ["COMP3314"] },
            { code: "COMP4511", name: "Principles of Deep Learning", credits: 6, category: "second-major", prerequisites: ["COMP3340"] },
            { code: "COMP4512", name: "Advanced Computer Vision", credits: 6, category: "second-major", prerequisites: ["COMP3317"] },
        ]
    },

    "stat-minor": {
        name: "Statistics",
        type: "minor",
        credits: 42,
        overlapNote: "Cannot combine with majors in Computing & Data Analytics, Decision Analytics, Risk Management, or Statistics.",
        courses: [
            { code: "SDST1018", name: "Foundations of Data Science", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST2601", name: "Probability and Statistics I", credits: 6, category: "second-major", prerequisites: ["MATH1013"] },
            { code: "SDST2602", name: "Probability and Statistics II", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST2604", name: "Intro to R/Python Programming and Data Analysis", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST3600", name: "Linear Statistical Analysis", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3602", name: "Statistical Inference", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3603", name: "Stochastic Processes", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3604", name: "Design and Analysis of Experiments", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3612", name: "Statistical Machine Learning", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3613", name: "Marketing Analytics", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3617", name: "Sample Survey Methods", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3620", name: "Modern Nonparametric Statistics", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3621", name: "Statistical Data Analysis", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3655", name: "Survival Analysis", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST4601", name: "Time-Series Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST4602", name: "Multivariate Data Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST4610", name: "Bayesian Learning", credits: 6, category: "second-major", prerequisites: ["SDST3602"] },
        ]
    },

    "phys-minor": {
        name: "Physics",
        type: "minor",
        credits: 42,
        overlapNote: "Requires Level 3+ in HKDSE Physics or equivalent.",
        courses: [
            // Core (6 cr)
            { code: "PHYS1250", name: "Fundamental Physics", credits: 6, category: "second-major", prerequisites: [] },
            // Introductory Electives (18 cr min)
            { code: "PHYS1150", name: "Problem Solving in Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS2055", name: "Introductory Relativity", credits: 6, category: "second-major", prerequisites: ["PHYS1150"] },
            { code: "PHYS2150", name: "Methods in Physics I", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS2155", name: "Methods in Physics II", credits: 6, category: "second-major", prerequisites: ["PHYS2150"] },
            { code: "PHYS2160", name: "Introductory Computational Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS2250", name: "Introductory Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS1150"] },
            { code: "PHYS2255", name: "Introductory Electricity and Magnetism", credits: 6, category: "second-major", prerequisites: ["PHYS1150"] },
            { code: "PHYS2261", name: "Introductory Heat and Thermodynamics", credits: 6, category: "second-major", prerequisites: ["PHYS1150"] },
            { code: "PHYS2265", name: "Introductory Quantum Physics", credits: 6, category: "second-major", prerequisites: ["PHYS1150"] },
            // Advanced Electives (18 cr min)
            { code: "PHYS3150", name: "Theoretical Physics", credits: 6, category: "second-major", prerequisites: ["PHYS2150"] },
            { code: "PHYS3151", name: "Machine Learning in Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS3350", name: "Classical Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS2150", "PHYS2250"] },
            { code: "PHYS3351", name: "Quantum Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS2150", "PHYS2265"] },
            { code: "PHYS3450", name: "Electromagnetism", credits: 6, category: "second-major", prerequisites: ["PHYS2150", "PHYS2255"] },
            { code: "PHYS3550", name: "Statistical Mechanics and Thermodynamics", credits: 6, category: "second-major", prerequisites: ["PHYS2150", "PHYS2261"] },
            { code: "PHYS3650", name: "Observational Astronomy", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS3653", name: "Astrophysics", credits: 6, category: "second-major", prerequisites: ["PHYS2250"] },
            { code: "PHYS3660", name: "Astronomy Laboratory", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS3750", name: "Foundations of Laser and Spectroscopy", credits: 6, category: "second-major", prerequisites: ["PHYS2255"] },
            { code: "PHYS3760", name: "Physics Laboratory", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS3850", name: "Physical Optics", credits: 6, category: "second-major", prerequisites: ["PHYS2250", "PHYS2255"] },
            { code: "PHYS3851", name: "Atomic and Nuclear Physics", credits: 6, category: "second-major", prerequisites: ["PHYS2265"] },
            { code: "PHYS4150", name: "Computational Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4151", name: "Data Analysis and Modeling in Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4351", name: "Advanced Quantum Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS3150", "PHYS3351"] },
            { code: "PHYS4450", name: "Advanced Electromagnetism", credits: 6, category: "second-major", prerequisites: ["PHYS3150", "PHYS3450"] },
            { code: "PHYS4550", name: "Advanced Statistical Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS3550"] },
            { code: "PHYS4551", name: "Solid State Physics", credits: 6, category: "second-major", prerequisites: ["PHYS3351"] },
            { code: "PHYS4650", name: "Stellar Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4652", name: "Planetary Science", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4653", name: "Selected Topics in Astrophysics and Cosmology", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4654", name: "General Relativity", credits: 6, category: "second-major", prerequisites: ["PHYS2055", "PHYS3350"] },
            { code: "PHYS4655", name: "Interstellar Medium", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4656", name: "Advanced Astrophysics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "PHYS4850", name: "Particle Physics", credits: 6, category: "second-major", prerequisites: ["PHYS3351"] },
            // Graduate courses (available to undergrads)
            { code: "PHYS7350", name: "Graduate Classical Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS3350"] },
            { code: "PHYS7351", name: "Graduate Quantum Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS3351"] },
            { code: "PHYS7450", name: "Graduate Electromagnetic Field Theory", credits: 6, category: "second-major", prerequisites: ["PHYS3450"] },
            { code: "PHYS7550", name: "Graduate Statistical Mechanics", credits: 6, category: "second-major", prerequisites: ["PHYS3550"] },
            { code: "PHYS7750", name: "Physics of Nanoelectronics", credits: 6, category: "second-major", prerequisites: [] },
        ]
    },

    "econ-minor": {
        name: "Economics",
        type: "minor",
        credits: 36,
        overlapNote: "MATH1013 overlaps with Economics minor requirement. No double-counting for major-minor — take a replacement elective.",
        courses: [
            { code: "ECON1210", name: "Introductory Microeconomics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ECON1220", name: "Introductory Macroeconomics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ECON2210", name: "Intermediate Microeconomics", credits: 6, category: "second-major", prerequisites: ["ECON1210"] },
            { code: "ECON2220", name: "Intermediate Macroeconomics", credits: 6, category: "second-major", prerequisites: ["ECON1220"] },
            { code: "ECON2252", name: "Theory of International Trade", credits: 6, category: "second-major", prerequisites: ["ECON1210"] },
            { code: "ECON2280", name: "Introductory Econometrics", credits: 6, category: "second-major", prerequisites: ["ECON1210"] },
            { code: "ECON4211", name: "Advanced Microeconomics", credits: 6, category: "second-major", prerequisites: ["ECON2210"] },
            { code: "ECON4221", name: "Advanced Macroeconomics", credits: 6, category: "second-major", prerequisites: ["ECON2220"] },
        ]
    },

    "fina-minor": {
        name: "Finance",
        type: "minor",
        credits: 36,
        overlapNote: "No double-counting for major-minor. Faculty Core courses cannot be shared with Math major.",
        courses: [
            // Faculty Core (24 cr)
            { code: "ACCT1101", name: "Introduction to Financial Accounting", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ECON1210", name: "Introductory Microeconomics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "FINA1310", name: "Corporate Finance", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ECON1280", name: "Analysis of Economic Data", credits: 6, category: "second-major", prerequisites: [] },
            // Additional Required
            { code: "ECON1220", name: "Introductory Macroeconomics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "FINA2320", name: "Investments and Portfolio Analysis", credits: 6, category: "second-major", prerequisites: ["FINA1310"] },
            // Electives
            { code: "FINA2322", name: "Derivatives", credits: 6, category: "second-major", prerequisites: ["FINA1310"] },
            { code: "FINA2330", name: "Financial Markets and Institutions", credits: 6, category: "second-major", prerequisites: ["FINA1310"] },
            { code: "FINA2331", name: "Management of Commercial Banks", credits: 6, category: "second-major", prerequisites: ["FINA1310"] },
            { code: "FINA2342", name: "Insurance: Theory and Practice", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ACCT3114", name: "Valuation Using Financial Statements", credits: 6, category: "second-major", prerequisites: ["ACCT1101"] },
        ]
    },

    "rm-minor": {
        name: "Risk Management",
        type: "minor",
        credits: 42,
        overlapNote: "Cannot combine with Statistics or Decision Analytics major.",
        courses: [
            { code: "SDST2601", name: "Probability and Statistics I", credits: 6, category: "second-major", prerequisites: ["MATH1013"] },
            { code: "SDST2602", name: "Probability and Statistics II", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST2604", name: "Intro to R/Python Programming and Data Analysis", credits: 6, category: "second-major", prerequisites: [] },
            { code: "SDST3609", name: "The Statistics of Investment Risk", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3610", name: "Risk Management and Insurance", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3612", name: "Statistical Machine Learning", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3615", name: "Practical Mathematics for Investment", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST3618", name: "Derivatives and Risk Management", credits: 6, category: "second-major", prerequisites: ["SDST2601"] },
            { code: "SDST4601", name: "Time-Series Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST4603", name: "Current Topics in Risk Management", credits: 6, category: "second-major", prerequisites: ["SDST3609"] },
            { code: "SDST4606", name: "Risk Management and Basel Accords", credits: 6, category: "second-major", prerequisites: ["SDST3609"] },
            { code: "SDST4607", name: "Credit Risk Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
            { code: "SDST4608", name: "Market Risk Analysis", credits: 6, category: "second-major", prerequisites: ["SDST3600"] },
        ]
    },

    "eee-minor": {
        name: "Electrical & Electronic Engineering",
        type: "minor",
        credits: 48,
        overlapNote: "Not applicable to BEng(CE), BEng(EE), BEng(ElecE). Requires HKDSE Math L3+ and Physics L3+. ENGG1310 cannot double-count with another programme.",
        courses: [
            // Core (12 cr)
            { code: "ENGG1310", name: "Electricity and Electronics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC2346", name: "Electric Circuit Theory", credits: 6, category: "second-major", prerequisites: ["ENGG1310"] },
            // Disciplinary Electives (36 cr from the following)
            { code: "ELEC2147", name: "Electrical Energy Technology", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC2243", name: "Introduction to Electricity and Magnetism", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC2245", name: "Control Systems I", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC2347", name: "Fundamentals of Optics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC2441", name: "Computer Organization and Microprocessors", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC2543", name: "Object-Oriented Programming and Data Structures", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC2544", name: "Introduction to Electronic Commerce and Financial Technology", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3142", name: "Electrical Energy Conversion", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3143", name: "Power Electronics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3241", name: "Signals and Linear Systems", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3243", name: "Fundamentals of Next-Generation Communications", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3244", name: "Digital Signal Processing", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3248", name: "Engineering Electromagnetism and Antenna Design", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3249", name: "Pattern Recognition and Machine Intelligence", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3342", name: "Digital System Design", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3347", name: "Electronic Materials and Quantum Physics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3349", name: "Optical Devices", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3350", name: "Electronic Circuits and Devices I", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3351", name: "Electronic Circuits and Devices II", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3441", name: "Computer Architecture", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3443", name: "Computer Networks", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3543", name: "Advanced Systems Programming", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3544", name: "Introduction to Data Analytics", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC3641", name: "Human Computer Interaction", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC4343", name: "Design of Digital Integrated Circuits", credits: 6, category: "second-major", prerequisites: [] },
            { code: "ELEC4344", name: "Advanced Electronic Circuits", credits: 6, category: "second-major", prerequisites: [] },
        ]
    },
};
